### PR TITLE
Purge MemFS

### LINKED ISSUE #581: introduce @inlang-git/fs to the codebase
Follow up of https://github.com/inlang/inlang/pull/580

- [x] Make memoryFs usable with isomorphic git (should be easy with node compatibility now)
- [x] #702
- [x] #704
- [x] Publish `@inlang-git/fs` to npm (required for `@inlang/core` which uses a subset of `Filesystem` for `$fs`)

Ideally, the tasks are complete by the end of this week in order to merge #559 and unblock #544

### LINKED ISSUE #702: Replace memfs across the entire mono repo with memoryFs
## Problem 

Memfs leads to problems in the editor. 

## Proposal

Replace memfs in the editor by our @inlang-git/fs implementation to streamline the filesystem across inlang.

### PR DESCRIPTION
**Pull request by araknast**
Purge memfs across the repo and replace it with our own `memoryFs`. Fixes #702 and  fixes #581.

### CODE REVIEW

**Comment by samuelstroschein** [comment]
Going to review it tomorrow or tuesday!

**Comment by samuelstroschein** [comment]
@araknast make sure to test PRs by running the editor. The following line lead to a crash an immediate crash when opening the editor:

https://github.com/inlang/inlang/blob/85c29fc8913d5ac7fac99b80a27372851a329246/source-code/website/src/pages/editor/%40host/%40owner/%40repository/State.tsx#L634-L637

A tricky line when testing the editor (without running it) because of `@ts-ignore` which led TypeScript ignoring the error.

**Comment by samuelstroschein** [comment]
Man sometimes i don't understand git. I rebase to avoid merge conflicts when merging to main. The result are merge conflicts after rebasing. Why?

**Comment by araknast** [comment]
> @araknast make sure to test PRs by running the editor. The following line lead to a crash an immediate crash when opening the editor:
> 
> https://github.com/inlang/inlang/blob/85c29fc8913d5ac7fac99b80a27372851a329246/source-code/website/src/pages/editor/%40host/%40owner/%40repository/State.tsx#L634-L637
> 
> A tricky line when testing the editor (without running it) because of `@ts-ignore` which led TypeScript ignoring the error.

Gotcha, will test with the editor in the future. I had been trying to avoid website builds since they overwhelm by pc a bit, but it seems they are good for catching errors like this.

**Pull request merged**
