### PR TITLE
ease development setup by using dev containers

### LINKED ISSUE #362: replace gitpod with dev container
## Problem 

https://github.com/inlang/inlang/issues/312
https://github.com/inlang/inlang/pull/347

## Solution 

- [ ] move to dev container
- [ ] load env file without doppler

### PR DESCRIPTION
**Pull request by samuelstroschein**
Introduces dev containers as development environment that replace gitpod. Closes #362, #347 and #312. 

The env varibales are now comitted in the repo to streamline dev setup.

All variables in the env file (for development) are public. A good alternative for not comitting the env file does not exist, see https://community.doppler.com/t/public-env-files-to-streamline-open-source-contributions/949.

### CODE REVIEW

**Comment by samuelstroschein** [comment]
This PR closes #347 and only introduces changes related to dev containers. @openscript I intended to minimize the merge conflicts. Other changes like vs code starting scripts can be re-introduced when you open the PR for the IDE extension.

**Comment by openscript** [comment]
Merge conflicts are no problem. It's a task I like to do 😊

I wonder why you didn't use `mcr.microsoft.com/vscode/devcontainers/typescript-node`?

**Comment by samuelstroschein** [comment]
Typescript is installed with NPM. No need for a global TypeScript installation. The image is thus smaller + has one dependency less + we can define the typescript version in https://github.com/inlang/inlang/blob/main/package.json

**Comment by openscript** [comment]
Seems to be a valid reason, as this template doesn't do that much more than the used template: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/typescript-node/.devcontainer/base.Dockerfile

**Pull request merged**
