### PR TITLE
Newsletter signup implementation

### PR DESCRIPTION
**Pull request by floriandwt**
## Newsletter signup form
- Added a signup form into the footer section of the website

### CODE REVIEW

**Comment by NilsJacobsen** [comment]
I like the behavior with the default toast. That works and I think it's consistent. Is the logic also intended to work? Cause I didn't get a mail or something? @floriandwt

**Comment by floriandwt** [comment]
@NilsJacobsen Thanks for the review – yes you're subscribed: https://docs.google.com/spreadsheets/d/1IzcozFvGQe15RvmwCqIRFhPkS-LmYXHr_PiNR0akYiA/

I have now activated the confirmation mail, feel free to try it again.

**Comment by NilsJacobsen** [comment]
Great it works 👍 

That's a minor thing. I wonder if the error handling of your API is that granular. 
image

I got this when trying to signup twice. We could show different error messages. Maybe an `already signed up` and `subscription request failed` as a distingtion.

**Review by NilsJacobsen — APPROVED** [review]
That is great, thanks @floriandwt . 🎉

**Comment by NilsJacobsen** [comment]
Could you investigate the test error? @floriandwt

**Comment by NilsJacobsen** [comment]
Is the fetch url an open api? Cause there is no token or key required? Can people abuse the link? If yes, we should call it serverside.

**Pull request merged**
