### PR TITLE
New landing page

### PR DESCRIPTION
**Pull request by NilsJacobsen**
New lading page implementation:
According to this: #416 

- Adjusted the layout component 
- Added new components for the different sections 
- Recorded feature videos (Can be changed with new features)
- Added basic responsiveness

### CODE REVIEW

**Comment by samuelstroschein** [comment]
Dope 🚀 The screen animations are really valuable. I found myself watching the entire editor animation. 

## Minor issues 

### 1. The footer "looks" broken on the editor 

Remove the lines? Or remove the footer from the editor? I vote for removing the lines but you decide.

  
CleanShot 2023-03-13 at 19 14 50@2x

CleanShot 2023-03-13 at 19 15 02@2x

**Comment by NilsJacobsen** [comment]
Gonna make the changes tomorrow morning an merge it. Will be merged by 7am. @samuelstroschein

**Comment by jannesblobel** [comment]
CleanShot 2023-03-13 at 20 48 13@2x

Some thoughts: 
The inlang icon in the left corner is a bit small compared to the buttons and the example logos at the bottom. And I'm Not sure if the Icon Left has the same height as the button and the right

**Comment by jannesblobel** [comment]
My opinion on the lines of the editor: it's not so important yet, because the  "editor" is a different initiative. 
 
> CleanShot 2023-03-13 at 19 15 02@2x

**Comment by jannesblobel** [comment]
Have you tried different heights of the header? I find the header a bit too high 


CleanShot 2023-03-13 at 20 58 59@2x

**Comment by jannesblobel** [comment]
Sorry for the different comments on the same page, 
It is not visible that you can scroll through this Website 


CleanShot 2023-03-13 at 21 03 21@2x

**Comment by jannesblobel** [comment]
The screencasts on the website are nice. I like them. But when you see the editor screencast on a Macbook Air screen, it's a bit overwhelming 

CleanShot 2023-03-13 at 21 06 34

**Comment by jannesblobel** [comment]
Oh, the content of the body is under the header.

CleanShot 2023-03-13 at 21 11 56@2x

**Comment by jannesblobel** [comment]
The container in the footer (number 2) does not have the same padding / there is no padding like the container in the body ( number 1) 

CleanShot 2023-03-13 at 21 16 39@2x

**Comment by jannesblobel** [comment]
I noticed you used different paddings in the footer than in the header. Is there a particular reason? 

CleanShot 2023-03-13 at 21 20 05@2x

**Comment by jannesblobel** [comment]
I don't know if the inlang logo in the footer is in the position place as the section headings. 

CleanShot 2023-03-13 at 21 23 27@2x

**Comment by jannesblobel** [comment]
In all other sections, this is a button, my first assumption was "npm inlang..." is clickable. Maybe we can make this as a button and on click a toast "copied to clipboard" opens?  

CleanShot 2023-03-13 at 21 26 35@2x

**Comment by jannesblobel** [comment]
What do you think of the outline on number 1? I like it more without the outline 

CleanShot 2023-03-13 at 21 32 05@2x
CleanShot 2023-03-13 at 21 32 36@2x

**Comment by jannesblobel** [comment]
I like the blue hover effect on the icons. The difference between grey and dark on the text buttons is relatively small :/ 

CleanShot 2023-03-13 at 21 34 58

**Comment by jannesblobel** [comment]
My last words to this landing page: 
I saw it only on a MacBook screen. Keep that in mind. 

More important is you both @NilsJacobsen  and @NiklasBuchfink, did a fantastic Job.  All my thoughts are on a high level, and you may disagree. Please take these as constructive feedback, not an attack on your great work. On the contrary, you have achieved to do what I never did. 

Let's celebrate the new inlang website made by @NilsJacobsen  and @NiklasBuchfink

**Comment by NilsJacobsen** [comment]
> Dope 🚀 The screen animations are really valuable. I found myself watching the entire editor animation.
> 
> ## Minor issues
> ### 1. The footer "looks" broken on the editor
> Remove the lines? Or remove the footer from the editor? I vote for removing the lines but you decide.
> 
> CleanShot 2023-03-13 at 19 14 50@2x
> 
> CleanShot 2023-03-13 at 19 15 02@2x
> 
> ### 2. We should compress the videos
> The videos are gigantic for web standards. The website loads 15MB :D SEO is not so important right now but 15MB is heavy
> 
> CleanShot 2023-03-13 at 19 36 49@2x

removed the lines on editor

**Comment by NilsJacobsen** [comment]
> CleanShot 2023-03-13 at 20 48 13@2x
> 
> Some thoughts: The inlang icon in the left corner is a bit small compared to the buttons and the example logos at the bottom. And I'm Not sure if the Icon Left has the same height as the button and the right

made the logo bigger (w-9 h-9 it's a bit more even with the buttons now, buttons are h-10 but that looks bulky)

**Comment by NilsJacobsen** [comment]
> Oh, the content of the body is under the header.
> 
> CleanShot 2023-03-13 at 21 11 56@2x

should be fixed now

**Comment by NilsJacobsen** [comment]
> I like the blue hover effect on the icons. The difference between grey and dark on the text buttons is relatively small :/
> 
> CleanShot 2023-03-13 at 21 34 58 [ CleanShot 2023-03-13 at 21 34 58 ](https://user-images.githubusercontent.com/72493222/224826178-d9bba2a4-63d0-4e55-927f-d393ae1ad611.gif) [ ](https://user-images.githubusercontent.com/72493222/224826178-d9bba2a4-63d0-4e55-927f-d393ae1ad611.gif)

Added blue hover to all links without a surface

**Comment by NilsJacobsen** [comment]
> Have you tried different heights of the header? I find the header a bit too high
> 
> CleanShot 2023-03-13 at 20 58 59@2x

Made the nav bar a bit smaller

**Comment by NilsJacobsen** [comment]
Thank you @samuelstroschein @jannesblobel for the feedback. Integrated some of the suggestions. We can talk about the rest in the future I would say.

**Pull request merged**
