### PR TITLE
fix language folder support

### PR DESCRIPTION
**Pull request by NiklasBuchfink**
This should tackle #966 & #976 for `plugin-i18next` and `plugin-json`

### CODE REVIEW

**Comment by NiklasBuchfink** [comment]
@samuelstroschein Metadata is deprecated and still used inside the plugin. As it was empty inside writeResources, the fileName is undefined and that's why there was always the file creation of  `undefined.json`.

Please review the changes and let me know, if the fix over `message.id.name!.split(".")[0])` instead of `message.metadata.fileName` is valid.

**Note:** The same fix still needs to be made within the `plugin-json`.

**Review by samuelstroschein — APPROVED** [review]
LGTM. 

Why did the other unit tests not catch the bug?

**Comment by samuelstroschein** [comment]
@NiklasBuchfink feel free to mark the PR as ready for review and immediately merge :)

BUT don't forget to: 

1. update the json plugin too
2. create patch notes with `npx changeset`

**Comment by NiklasBuchfink** [comment]
@samuelstroschein I tested it locally. 

#966 is fixed with the change.

#976 not:
- correct in the local state of the editor (writing to fs seems to be correct.)
- commit is still empty (`filesWithUncommittedChanges` is still empty)

See https://inlang.com/editor/github.com/NiklasBuchfink/nextjs-i18next

I dig deeper

**Comment by NiklasBuchfink** [comment]
Empty commits bug is fixed.

Last thing to be fixed: AddLanguage support. This is broken since the PR Reduce commits.

**Pull request merged**
