### PR TITLE
fail over on lint error and provide lint summary

### PR DESCRIPTION
**Pull request by felixhaeberle**
this PR changes the default behavior of lint report to fail on errors and give a table output of the messages & a summary table with total numbers.

### CODE REVIEW

**Review by samuelstroschein — APPROVED** [review]

**Comment by felixhaeberle** [comment]
added docs & changeset

**Comment by samuelstroschein** [comment]
@felixhaeberle I meant adding a description of the `no-fail` option to the CLI output to provide in-context help.

**Comment by felixhaeberle** [comment]
@samuelstroschein Is this necessary or a nice-to have?

**Comment by samuelstroschein** [comment]
@felixhaeberle probably necessary to avoid people joining our discord and open "why is this suddenly failing" questions

**Comment by felixhaeberle** [comment]
added it 👍

**Review by samuelstroschein — APPROVED** [review]
❤️

**Pull request merged**
