### PR TITLE
Docs flow and content

### PR DESCRIPTION
**Pull request by NilsJacobsen**
Hey folks, 

this is the draft for the new docs.
We plan to merge it tomorrow.

**What changed:**
- New structure (getting started, apps, plugins, sdk, guides, core, contributing)
- Updated styling and js DX in Docs
- Updated images
- Updated content

**We need your help in order to ship this fast:**
- IDE extension @felixhaeberle could you integrate your readme / write it from the beginning (maybe needed cause we need the header, take a look at web editor).
- CLI we currently use CLI readme, could @felixhaeberle review this and work on product content (benefit, feature etc. right now it is more like api docs, take a look at web editor)
- @inlang/team checkout the introduction page this page is difficult from a communication standpoint. Please request changes
- @ivanhofer can you check the SDK docs (there is not a lot that changed, just to double check)
- In generell feedback is very welcome

> Keep in mind: We want to merge tomorrow, so the devs can get a nice experience again.

**Should close:**
- https://github.com/inlang/inlang/issues/755
- https://github.com/inlang/inlang/issues/863
- https://github.com/inlang/inlang/issues/778
- https://github.com/inlang/internal/issues/25

### CODE REVIEW

**Comment by NilsJacobsen** [comment]
Sneak peak:
image

**Comment by felixhaeberle** [comment]
@NiklasBuchfink @NilsJacobsen 

Already looks awesome!! 🎉🙏
Will add my parts tomorrow.

wow

**Comment by jannesblobel** [comment]
MacBook screen, can you change the box size to the above box size? 
CleanShot 2023-06-07 at 07 17 03@2x

**Comment by jannesblobel** [comment]
I would collect all the information about plugins at one point. I think there's no extra point need it for the plugin and registry right now

 CleanShot 2023-06-07 at 07 20 30@2x

**Comment by jannesblobel** [comment]
'Build apps on inlang' should be called "Build apps on Lisa" isn't it?

**Comment by jannesblobel** [comment]
But You improved the UX a lot. I like the small thinks <3 
great job :)

**Comment by samuelstroschein** [comment]
> @jannesblobel I would collect all the information about plugins at one point. I think there's no extra point need it for the plugin and registry right now

I would split both. The plugin registry should be purely focused on "find a plugin you need". While custom plugin should be "no plugin exists, create your own". Putting both in one flow could mix both flows. 

> @jannesblobel  'Build apps on inlang' should be called "Build apps on Lisa" isn't it?

Nope. Build apps on inlang refers to using `core` to build own inlang apps. A better phrasing could be "build your own inlang app".

**Comment by felixhaeberle** [comment]
@NilsJacobsen I'll review this afternoon.

**Comment by felixhaeberle** [comment]
@NilsJacobsen What are the reference values for the sidebar text size? Are they the same like on vuejs.com or Next.js because they seem 1px or 2px too small. More feedback will come soon but that's what I registered immediately.

**Comment by NilsJacobsen** [comment]
@felixhaeberle it's inspired by vue.js docs

**Comment by felixhaeberle** [comment]
Bildschirmfoto 2023-06-07 um 12 36 49

Can we get those for the README too? I love them!! So easy to see how you can engage and how popular a project is.

**Comment by NiklasBuchfink** [comment]
@felixhaeberle so instead of this banner?
image

**Comment by samuelstroschein** [comment]
@NiklasBuchfink npm downloads and package version doesn't make sense because we have multiple apps. removing npm from the badges leaves us with what we basically have right now.

**Comment by NiklasBuchfink** [comment]
Well, then we leave it as it is 👍

**Comment by NilsJacobsen** [comment]
> @NilsJacobsen @NiklasBuchfink Can we get some feedback on the rating menu at the bottom? It doesn't react on clicking atm. At least not for me. Should be a small state in the button that says: "Thanks for your feedback!".

MVP style i was fine with reload as 'your form was submitted' which is still far from great but we want to ship it in a week right:D 

I'm sure we make a follow up on certain things.

**Comment by felixhaeberle** [comment]
@NilsJacobsen This is just one state for the rating button, it doesn't take longer than 45sec to implement that.

**Comment by NilsJacobsen** [comment]
Gonna merge that. We gonna make a follow up issue for stuff that is gonna planned for the next docs sprint.

**Pull request merged**
