### PR TITLE
#658: make `@inlang/sdk-js` work on windows machines

### LINKED ISSUE #658: make `@inlang/sdk-js` work on windows machines
I haven't tested it yet, but we have hardcoded unix-paths, so it will probably not work on windows machines.

### PR DESCRIPTION
**Pull request by ivanhofer**
closes #658

### CODE REVIEW

**Comment by ivanhofer** [comment]
@samuelstroschein fyi those were the necessary changes to make `build`, `dev`, `test` and `clean` work on windows. I didn't check other commands, but we can add them when someone needs them.

**Comment by samuelstroschein** [comment]
@ivanhofer lgtm. merge if ready

**Comment by samuelstroschein** [comment]
Deployment fails on UNIX machines.

CleanShot 2023-05-11 at 11 57 12@2x

**Comment by ivanhofer** [comment]
Does it run locally on your machine?

**Comment by samuelstroschein** [comment]
Yes it does. 

Hopefully fixed with https://github.com/inlang/inlang/commit/78d93e696dee1e507996bd667b584c4f4c3777fc

**Pull request merged**
